name: Release

on:
  release:
    types:
      - "published"
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction --no-ansi

    - name: Build package
      run: poetry build

    - name: Publish package
      if: github.event_name == 'release'
      env:
        PYPI_USERNAME: __token__
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish --build --no-interaction --no-cache -u "${PYPI_USERNAME}" -p "${PYPI_TOKEN}"

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/aaomidi/certbot-dns-google-domains

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
